const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';
const LOGOUT = 'LOGOUT';
const GET_ALL_USERS = 'GET_ALL_USERS';
const DELETE_USER = 'DELETE_USER';
const ADD_PROJECT = 'ADD_PROJECT';
const GET_PROJECTS_BY_ID = 'GET_PROJECTS_BY_ID';
const DELETE_PROJECT = 'DELETE_PROJECT';
const GET_ACCOUNT_INFO = 'GET_ACCOUNT_INFO';

export { LOGIN_SUCCESS, LOGIN_FAIL, REGISTER_FAIL, REGISTER_SUCCESS,
  LOGOUT, GET_ALL_USERS, DELETE_USER, ADD_PROJECT, GET_PROJECTS_BY_ID, DELETE_PROJECT, GET_ACCOUNT_INFO };
